[package]
name = "rust-lockfree"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
crossbeam-epoch = "0.9.18"
once_cell = "1.20.2"
array-init = "2.1.0"
parking_lot = "0.12.3"

[dev-dependencies]
criterion = "0.5.1"